# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4bd1fba2d2f64dd2e103acf1eefd8fb1a30974fee18fc8ab62612222e1b4eaefa832bff4358320a76652a1765e4f7f015c80c62f92c58aa8da9d5fc43493876f

test:
  secret_key_base: 8cea5a4a562cba5068c534ed3757fd9ee74ff20dc00fa400315b43e551042de510fd52167764435f78c2c73173c16c51d4da954fe5d0bc0cfecb5bcd851105f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
